### ISSUE TITLE
use terra interface

### ISSUE THREAD

**Issue by rhijmans** [adamlilith/enmSdmX#22]
Hi Adam, 

In two instances the enmSdmX package uses
  
```
ext <- terra::ext(x)@ptr$vector
```

That breaks with the development version of terra.  The `@ptr$` methods are not safe for use in other packages. Can you use the "official" interface instead? Something like this:

```
ext <- as.vector( terra::ext(x) )
```
Thanks!

**Comment by rhijmans** [comment]
Can you please fix this?

**Comment by adamlilith** [comment]
So sorry! I just saw this.  The issue has been fixed.
