### ISSUE TITLE
bug in trainGAM when interactions disabled

### ISSUE THREAD

**Issue by ptitle** [adamlilith/enmSdmX#47]
Hi Adam,

The documentation for trainGAM states that if `interaction = NULL`, then interaction terms are not included. However, a check for this is not currently implemented, and as a result, `interaction`, which is by default a type of smoother, gets concatenated, for example leading to `(bio1, bio2, bs = 'cs')` (so an empty variable gets pasted to the front) instead of `te(bio1, bio2, bs = 'cs')`, and this of course ultimately leads to errors. 

A simple fix though... just need to encase lines 130 - 164 with `if (!is.null(interaction)) {}`, at least as far as I can tell.

**Comment by adamlilith** [comment]
Thanks for catching this, too, Pascal!  I'll incorporate your code into the package by the end of the weekend.
Adam

**Comment by adamlilith** [comment]
Issue fixed in `enmSdmX` 1.1.9, which is now the master and has been pushed to CRAN. Thanks again, Pascal!
